### PR TITLE
Upgrade laravel support to ^8.25

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by MaxKorlaar** [comment]
Thank you for your contribution! I value the package `laravel-ide-helper` however, so I'd like to keep that in for now.

**Comment by lloricode** [comment]
> `laravel-ide-helper` however, so I'd like to keep that in for now.

what do you mean? btw, sorry not mentioning that, it suppose to remove that in production, since  it never usu that in production level

when deploying this, we should run `composer i --no-dev -o` for production, to exclude all none production packages,

**Comment by MaxKorlaar** [comment]
Ah, right, apologies. I missed that! I will check it out later this week, thank you!

**Comment by lloricode** [comment]
Hi @MaxKorlaar can we exclude .idea folder? since we have different environment, so less confusing

**Comment by lloricode** [comment]
just made PR https://github.com/MaxKorlaar/hypixel-signatures/pull/98

**Comment by MaxKorlaar** [comment]
Thank you. I noticed that PR. I will comment on it, because I'd prefer to keep that folder.

**Review by MaxKorlaar — APPROVED** [review]

**Pull request merged**
